openapi: 3.0.1
info:
  title: Duplicate schema resolved example
  version: '1.0.0'
paths:
  /dummy:
    get:
      operationId: getDummy
      responses:
        '200':
          description: OK
components:
  schemas:
    HelloEnum:
      type: string
      enum:
        - HI
        - OHA
    BlankEnum:
      type: string
      enum:
        - ''
    NullEnum:
      enum:
        - null
    ItemHello:
      nullable: true
      oneOf:
        - $ref: '#/components/schemas/HelloEnum'
        - $ref: '#/components/schemas/BlankEnum'
        - $ref: '#/components/schemas/NullEnum'
    Item1:
      type: object
      properties:
        hello:
          $ref: '#/components/schemas/ItemHello'
    Item2:
      type: object
      properties:
        hello:
          $ref: '#/components/schemas/ItemHello'
