/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * Duplicate schema reproduction
 * OpenAPI spec version: 1.0.0
 */

export type HelloEnum = typeof HelloEnum[keyof typeof HelloEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HelloEnum = {
  HI: 'HI',
  OHA: 'OHA',
} as const;
