/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * Duplicate schema reproduction
 * OpenAPI spec version: 1.0.0
 */
import type { Item1Hello } from './item1Hello';

export interface Item1 {
  /** @nullable */
  hello?: Item1Hello;
}
