/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * Duplicate schema reproduction
 * OpenAPI spec version: 1.0.0
 */

export type NullEnum = typeof NullEnum[keyof typeof NullEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NullEnum = {
} as const;
