/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * Duplicate schema reproduction
 * OpenAPI spec version: 1.0.0
 */
import { HelloEnum } from './helloEnum';
import { BlankEnum } from './blankEnum';

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Item1Hello = {...HelloEnum,...BlankEnum,} as const