/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * Duplicate schema reproduction
 * OpenAPI spec version: 1.0.0
 */


/**
 * @nullable
 */
export type Item2Hello = typeof Item2Hello[keyof typeof Item2Hello]  | null;
-next-line @typescript-eslint/no-redeclare
export const Item2Hello = {...HelloEnum,...BlankEnum,} as const