/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * Duplicate schema reproduction
 * OpenAPI spec version: 1.0.0
 */


/**
 * @nullable
 */
export type Item1Hello = typeof Item1Hello[keyof typeof Item1Hello]  | null;
} from './nullEnum';

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Item1Hello = {...HelloEnum,...BlankEnum,...NullEnum,} as const