/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * Duplicate schema reproduction
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export const getDummy = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/dummy`,options
    );
  }

export type GetDummyResult = AxiosResponse<void>
